name: Build Cava

on: push

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Visual Studio
      uses: microsoft/setup-msbuild@v2

    - name: Build Cava
      run: msbuild cava_win/cava_win.sln /p:Configuration=Release

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: |
          **/Release/**